Iter5
personage-hub/metrics-tracker pull request #5
Opened 2023-07-16 12:29 UTC by personage-hub

2023-07-19 13:41 UTC, kilchik requested changes

2023-07-19 13:41 UTC, kilchik commented on cmd/agent/flags.go
> +	reportInterval = time.Duration(reportIntervalParam) * time.Second
Здесь дважды дублируются строчки

2023-07-19 13:41 UTC, kilchik commented on cmd/agent/flags.go
> +	serverAddress       string
Старайся не создавать глобальные объекты никогда, единственным возможным исключением на практике может стать logger. Глобальные объекты чреваты
* огромными затруднениями при написании тестов
* сложноотловимыми багами, связанными с рейсами
* сложноотловимыми багами в целом, потому что к объекту есть доступ из любого куска кода (в данном случае в рамках одного пакета), очень сложно локализовать изменение, приведшее к багу

Стоит выделить отдельную структуру config со всеми параметрами и инициализировать ее в main

2023-07-19 13:41 UTC, kilchik commented on cmd/agent/main.go
> +var metricFuncMap = map[string]func(*runtime.MemStats) float64{
Глобальных объектов быть не должно
Кроме того, доступ к мапе на чтение+запись тут осуществляется из двух горутин - мапы в Go не являются потокобезопасным примитивом, стало быть их нужно защитить мьютексом или переделать логику обновления и отправки метрик, подробности ниже

2023-07-19 13:41 UTC, kilchik commented on cmd/agent/main.go
> +	go startPolling(storage)
Эти две функции можно выполнять в одной горутине без потери смысла, для этого можно воспользоваться конструкцией select, например, так
```
tickerPoll := time.NewTicker(pollInterval)
tickerReport := time.NewTicker(pollReport)
select {
case <-tickerPoll.C:
  collectMetrics()
case <-tickerReport.C:
  update...
```

2023-07-19 13:41 UTC, kilchik commented on cmd/agent/main.go
> +	go startPolling(storage)
В этом случае мапу можно не защищать от конкурретного доступа

2023-07-19 13:41 UTC, kilchik commented on cmd/agent/main.go
> +		panic(err)
Никогда нельзя обрабатывать ошибки через panic (кроме редких исключений, в рамках курса их нет). panic приведет к аварийному завершению, а наши сервисы должны поддерживать работоспособность при любых ошибках
Более того Go навязывает нам явную обработку ошибок. В данном случае ошибку следует вернуть вызывающей функции. Кроме того важно не просто возвращать ошибку, но обрамлять ее описанием того, где она произошла. Только так можно будет однозначно определить, в каком месте произошла ошибка, и кто пытался ее обработать. 
Для обрамления ошибки можно воспользоваться либо пакетом `github.com/pkg/errors` и обернуть функцией `errors.Wrap`, либо стандартным пакетом fmt `fmt.Errorf("process request: %w", err)`

2023-07-19 13:41 UTC, kilchik commented on internal/storage.go
> +	gauge   map[string]float64
Эти мапы нужно защитить от конкуррентного доступа на чтение+запись

2023-07-19 13:41 UTC, kilchik commented on cmd/server/main.go
> +	s := r.Context().Value(storageKeyContextKey).(*internal.MemStorage)
Context не следует использовать для передачи структур или бизнес-параметров. Есть редкие случаи, в которых передача параметров через контекст целесообразна (в основном вспомогательные параметры для трейсинга/логов). Параметры в context нетипизированы, а значит компилятор не проверит, что мы через него прокидываем
storage следует прокидывать в сервер через конструктор вспомогательной структуры (например, server), а хэндлеры - сделать методами этой структуры (тогда у них будет доступ до storage)

2023-07-19 14:21 UTC, personage-hub commented on cmd/agent/flags.go
> +	reportInterval = time.Duration(reportIntervalParam) * time.Second
мдя, обидно такое увидеть (

2023-07-25 13:39 UTC, kilchik approved these changes

2023-07-25 13:54 UTC, merged